menu:
  Startseite: https://www.felix-klauke.com
  Blog: https://blog.felix-klauke.com
  Projekte: https://www.github.com/FelixKlauke

excerpt_link: Weiterlesen

favicon: favicon.ico

less:
  paths: [css]