menu:
  Startseite: https://blog.klauke-enterprises.com
  Blog: https://blog.klauke-enterprises.com
  Projekte: https://blog.klauke-enterprises.com

excerpt_link: Weiterlesen

favicon: favicon.ico

less:
  paths: [css]
